name: update
on: push

jobs:
  Build:
    name: Environment Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm install
        
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"
      
      - name: Publish update
        run: eas update --auto
      - name: 👷 Build android app
        continue-on-error: true
        run: |
          eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=preview

      - name: 👷 Build ios app
        continue-on-error: true
        run: |
          eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=ios \
          --profile=preview
      - name: upload Apks artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: apks
          path: |
            ./app-build
